info:
  contact: {}
paths:
  /api/v1/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Email
        in: query
        name: email
        required: true
        type: string
      - description: Password(RSA Encrypted)
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login
      tags:
      - User
  /api/v1/ping:
    get:
      consumes:
      - application/json
      description: Ping-Pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping pong
      tags:
      - Ping
swagger: "2.0"
